name: CI

on:
  push:

jobs:
  static-analysis: #정적분석(mypy, black, ruff)
    runs-on: ubuntu-22.04 #실제 프로덕션에서는 모든 버전을 고정하는 것이 좋다.
    # 예기치 못한 버전 상승으로 장애가 발생하는 것을 막기 위해 버전을 고정하는 것이좋음.

    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.2.1

      - name: Register Poetry bin
        run: echo "${HOME}/.poetry/bin" >> %GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run Black
        run: poetry run black . --check

      - name: Run Ruff
        run: |
          poetry run ruff check --select I
          poetry run ruff check 

      - name: Run Mypy
        run: poetry run mypy .

  test: #전체테스트
    runs-on: ubunto 22.04
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.2.1

      - name: Register Poetry bin
        run: echo "${HOME}/.poetry/bin" >> %GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: |
          poetry run coverage run -m pytest .
          poetry run coverage report -m